name: compile assets

on: [push]

permissions:
  contents: write

jobs:
  compile:
    uses: laravel/.github/.github/workflows/compile-assets.yml@main
    with:
      cmd: build
      build_path: dist
